---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jingle
  namespace: mc
spec:
  chart:
    git: git@github.com:HRZNStudio/playhrzn-k8s
    ref: master
    path: charts/minecraft
  values:
    # ref: charts/minecraft/values.yaml
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - mc-jingle-minecraft
                - key: app
                  operator: NotIn
                  values:
                    - mc-rr5-minecraft
                    - mc-yogs-minecraft
                    - mc-st-minecraft
            topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 8Gi
        cpu: "1"
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 10
    minecraftServer:
      image: itzg/minecraft-server:openj9@sha256:645a39dd29045496fc3f580d2121e0e7edf83331fb754f185e073adf63ff1e50
      eula: "TRUE"
      version: "1.15.2"
      type: "PAPER"
      maxWorldSize: 29999984
      maxtickTime: -1
      memory: 8G
      annotations:
        external-dns.alpha.kubernetes.io/hostname: jingle.mc.playhrzn.com
      rcon:
        enabled: true
        serviceType: NodePort
      rconWebAdmin:
        enabled: true
        image: cwlf/rcon:latest@sha256:e6d0d325f9686c00f8b4b50afd9ef7a03a5bf0c305e7567db008d8679163c6b1
        websocketUrlSsl: "wss://jingle-rwa-ws.mc.playhrzn.com"
        serviceType: NodePort
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
        webIngress:
          annotations:
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/url: https://jingle-rwa.mc.playhrzn.com
            forecastle.stakater.com/icon: https://brainfoolong.github.io/rcon-web-admin/images/logo.png
            forecastle.stakater.com/appName: "RCON Web Admin"
            forecastle.stakater.com/group: "jingle"
            external-dns.alpha.kubernetes.io/hostname: jingle-rwa.mc.playhrzn.com
        websocketIngress:
          hostname: jingle-rwa-ws.mc.playhrzn.com
          annotations:
            external-dns.alpha.kubernetes.io/hostname: jingle-rwa-ws.mc.playhrzn.com
      cloudCommander:
        enabled: true
        auth: false
        image: coderaiser/cloudcmd:14.5.1-alpine@sha256:4d78e27eeb4393ef330b8121c84b7a78b499ee6d364bea3f697523165e292d38
        serviceType: NodePort
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            external-dns.alpha.kubernetes.io/hostname: jingle-files.mc.playhrzn.com
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/url: https://jingle-files.mc.playhrzn.com
            forecastle.stakater.com/icon: https://cloudcmd.io/img/logo/cloudcmd.png
            forecastle.stakater.com/appName: "File Manager"
            forecastle.stakater.com/group: "jingle"
    extraEnv:
      GENERIC_PACK: "https://cdn.hrzn.studio/jingle-server-staging.zip"
      GENERIC_PACK_STRIP_DIRS: "0"
      OVERRIDE_SERVER_PROPERTIES: "1"
      PAPERBUILD: "273"
    persistence:
      dataDir:
        enabled: true
        Size: 5Gi
      storageClass: ebs-sc
      volumeName: pvc-92fe93df-0396-41e0-b851-63412aa0736f
