---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: filebeat
  namespace: elastic-stack
spec:
  releaseName: filebeat
  chart:
    repository: https://helm.elastic.co
    name: filebeat
    version: 7.8.0
