---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx/
    name: ingress-nginx
    version: 2.0.3
  values:
    fullnameOverride: ingress-nginx
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-2:521397258504:certificate/30948eb5-f96e-423d-8eec-cb26cb459de6
          service.beta.kubernetes.io/aws-load-balancer-type: elb
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
        targetPorts:
          http: tohttps
          https: http
      containerPort:
        http: 80
        https: 80
        tohttps: 2443
      config:
        use-proxy-protocol: "true"
        proxy-real-ip-cidr: 192.168.0.0/16
        use-forwarded-headers: "true"
        http-snippet: |
          server {
            listen 2443;
            return 308 https://\$host\$request_uri;
          }
